/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIMessage: typeof import('./src/components/AIMessage.vue')['default']
    BAlert: typeof import('bootstrap-vue-next')['BAlert']
    BButton: typeof import('bootstrap-vue-next')['BButton']
<<<<<<< Updated upstream
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BToastOrchestrator: typeof import('bootstrap-vue-next')['BToastOrchestrator']
    ChatInput: typeof import('./src/components/ChatInput.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    ChatMessages: typeof import('./src/components/ChatMessages.vue')['default']
    Markdown: typeof import('./src/components/Markdown.vue')['default']
    ProfileIcon: typeof import('./src/components/ProfileIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserMessage: typeof import('./src/components/UserMessage.vue')['default']
=======
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BInput: typeof import('bootstrap-vue-next')['BInput']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
>>>>>>> Stashed changes
  }
}
